PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT (?albumString) AS ?ALBUM_NAMES SUM(?lengthInInteger) AS ?LENGTH  WHERE {
   ?albumNames dbpprop:totalLength ?totalLength .
   ?albumNames dbpprop:name ?albumString .
  ?albumNames dbpprop:length ?length .
  BIND(xsd:integer(?length) AS ?lengthInInteger)
   ?albumNames <http://dbpedia.org/property/title> ?songNames .
    {SELECT ?albumNames WHERE {?albumNames <http://dbpedia.org/ontology/artist> <http://dbpedia.org/resource/Megadeth> .}} 
}
  GROUP BY (?albumString)
  HAVING (count(?songNames)>10)
  ORDER BY(?albumString) 
  LIMIT 10
