PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX dbpp: <http://dbpedia.org/property/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX db: <http://dbpedia.org/>
PREFIX dbpr: <http://dbpedia.org/resource/>
PREFIX dbprop: <http://dbpedia.org/property/>

SELECT DISTINCT ?campusType AS ?CAMPUS_TYPE, count(?publicUniversitiesInLA) as ?NUMBER_OF_UNIVERSITIES WHERE 
{
  {
      ?publicUniversitiesInLA <http://dbpedia.org/ontology/type> <http://dbpedia.org/resource/Public_university> .
  }
  {
    {
      ?publicUniversitiesInLA dbpprop:location <http://dbpedia.org/resource/Los_Angeles> .
    }
    UNION
    {
      ?publicUniversitiesInLA dbpedia-owl:city <http://dbpedia.org/resource/Los_Angeles> .
    }
  }
{?publicUniversitiesInLA dbpprop:campus ?campusType .}
UNION
{?publicUniversitiesInLA dbpprop:campusType ?campusType .}


}GROUP BY (?campusType)